#!/usr/bin/env bash

# Generate a default-env.json file - default-env-gen

# Expects a single mandatory argument - a temporary app name
# Produces a default-env.json file containing the VCAP_SERVICES
# JSON data.

# As a minimum, it will bind the enterprise messaging service
# instance. It will also check for a destination service
# instance and an xsuaa service instance, with specific names,
# and bind those if it finds them.

declare instance_enterprise_messaging=emdev
declare targetfilename=default-env.json
declare sedcommandfile=default-env-gen.sed

# shellcheck disable=SC2034
declare instance_destination=destination-lite
# shellcheck disable=SC2034
declare instance_xsuaa=xsuaa-application

main() {
  local appname=$1
  local instance=${2:-$instance_enterprise_messaging}

  # Remove any existing dir and app
  rmdir "$appname" 2>/dev/null
  cf d -f "$appname" 2>/dev/null

  # Create new temp dir and deploy
  mkdir "$appname"
  cf push -c null \
    -k 64M \
    -m 32M \
    --no-route \
    --no-start \
    "$appname" "$appname"

  # Remove dir
  rmdir "$appname" 2>/dev/null

  # Bind the SAP Enterprise Messaging service instance to the app
  cf bind-service "$appname" "$instance"

  # If present, also bind the destination and xsuaa service instances
  for i in destination xsuaa; do
    local name="instance_$i"
    cf service "${!name}" > /dev/null 2>&1 \
      && cf bind-service "$appname" "${!name}"
  done

  # Request environment info
  cf env "$appname" | sed -n -f "$sedcommandfile" > "$targetfilename"

}

if [[ $# -eq 0 ]]; then
  echo Usage: "$(basename "$0") <temporary-app-name>"
  exit 1
fi

main "$@"
