#!/bin/sh

case $1 in
  secret)
    kubectl replace --force -f secret.yaml -n default
    ;;
  deployment)
    kubectl replace --force -f deployment.yaml -n default
    ;;
  all|both)
    kubectl replace --force -f secret.yaml -n default
    kubectl replace --force -f deployment.yaml -n default
    ;;
  *)
    echo "Usage: k8s_deploy {secret|deployment|all}"
esac
