#!/usr/bin/env bash

usage() {
  declare scriptname=$1
  echo "Usage: $scriptname <customerid>"
}

main() {
  declare customer=$1
  if [[ -z "$customer" ]]; then
    usage "$(basename "$0")" && exit 1
  fi

  curl --request DELETE \
    "$rooturl/teched/CharityEntry('$customer')"
}

declare rooturl="https://brain.c210ab1.kyma.shoot.live.k8s-hana.ondemand.com"
main "$@"
