---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name: calc-service
  template:
    metadata:
      labels:
        name: calc-service
    spec:
      containers:
        - name: application
          image: ghcr.io/sap-samples/developer-keynote-2020-calculationservice:latest
          imagePullPolicy: Always # change to pull after testing
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 1000Mi
            requests:
              memory: 32Mi
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: calc-service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    name: calc-service

---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: calc-service
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: calc-service
    port: 8080
    host: calc-service
  rules:
    - path: /.*
      methods: ["GET"]
      accessStrategies:
        - handler: noop
          config: {}
