#!/usr/bin/env bash

# Set up test forked repo based on an existing fork - setup-test-fork

set -o errexit

declare reponame=teched2020-developer-keynote

doesexist() {
  gh repo view "$1" >/dev/null 2>&1
}

main() {

  local username=$1

  # Check a username has been specified
  if [[ -z "$username" ]]; then
    echo "Usage: 1-setup <GitHub username>"
    exit 1
  fi

  # Check that there is a repo for that specified user
  if ! doesexist "$username/$reponame"; then
    echo "No repo $reponame exists for username $username - aborting"
    exit 1
  fi

  # Check to make sure there isn't already a fork in my user space
  if doesexist "$reponame"; then
    echo "Repo $reponame already exists on GitHub - aborting"
    exit 1
  fi

  gh repo clone "$username/$reponame"  # clone an existing fork of the repo
  cd $reponame || exit                 # move into the clone
  git remote remove origin             # remove link to source repo
  gh repo create $reponame --public -y # create new repo in qmacro
  git push origin main                 # push clone contents to new repo
  cd ..                                # move back up a level
  rm -rf $reponame                     # remove the clone

}

main "$@"

